# TCL File Generated by Component Editor 12.1sp1
# Tue Apr 16 17:35:02 BST 2013
# DO NOT MODIFY


# 
# Sobel_Instruction_Set "Sobel_Instruction_Set" v1.0
# Rafael Waldo Delgado Doblas 2013.04.16.17:35:02
# Juego de instrucciones que agiliza la ejecucion del algoritmo Sobel
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module Sobel_Instruction_Set
# 
set_module_property DESCRIPTION "Juego de instrucciones que agiliza la ejecucion del algoritmo Sobel"
set_module_property NAME Sobel_Instruction_Set
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MisComponentes
set_module_property AUTHOR "Rafael Waldo Delgado Doblas"
set_module_property DISPLAY_NAME Sobel_Instruction_Set
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SIS
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file SIS.v VERILOG PATH SIS.v
add_fileset_file ram_r.v VERILOG PATH ram_r.v
add_fileset_file ram_w.v VERILOG PATH ram_w.v
add_fileset_file FrameWriter.v VERILOG PATH FrameWriter.v
add_fileset_file AGrises.v VERILOG PATH AGrises.v
add_fileset_file Sobel.v VERILOG PATH Sobel.v
add_fileset_file Sobel_cache.v VERILOG PATH Sobel_cache.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH ENABLED false
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADD_WIDTH INTEGER 32
set_parameter_property ADD_WIDTH DEFAULT_VALUE 32
set_parameter_property ADD_WIDTH DISPLAY_NAME ADD_WIDTH
set_parameter_property ADD_WIDTH TYPE INTEGER
set_parameter_property ADD_WIDTH ENABLED false
set_parameter_property ADD_WIDTH UNITS None
set_parameter_property ADD_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADD_WIDTH HDL_PARAMETER true
add_parameter BURST_WIDTH_W INTEGER 5
set_parameter_property BURST_WIDTH_W DEFAULT_VALUE 5
set_parameter_property BURST_WIDTH_W DISPLAY_NAME BURST_WIDTH_W
set_parameter_property BURST_WIDTH_W TYPE INTEGER
set_parameter_property BURST_WIDTH_W ENABLED false
set_parameter_property BURST_WIDTH_W UNITS None
set_parameter_property BURST_WIDTH_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_WIDTH_W HDL_PARAMETER true
add_parameter BURST_WIDTH_R INTEGER 6
set_parameter_property BURST_WIDTH_R DEFAULT_VALUE 6
set_parameter_property BURST_WIDTH_R DISPLAY_NAME BURST_WIDTH_R
set_parameter_property BURST_WIDTH_R TYPE INTEGER
set_parameter_property BURST_WIDTH_R ENABLED false
set_parameter_property BURST_WIDTH_R UNITS None
set_parameter_property BURST_WIDTH_R ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_WIDTH_R HDL_PARAMETER true
add_parameter BYTE_ENABLE_WIDTH INTEGER 4
set_parameter_property BYTE_ENABLE_WIDTH DEFAULT_VALUE 4
set_parameter_property BYTE_ENABLE_WIDTH DISPLAY_NAME BYTE_ENABLE_WIDTH
set_parameter_property BYTE_ENABLE_WIDTH TYPE INTEGER
set_parameter_property BYTE_ENABLE_WIDTH ENABLED false
set_parameter_property BYTE_ENABLE_WIDTH UNITS None
set_parameter_property BYTE_ENABLE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTE_ENABLE_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH_LOG2 INTEGER 8
set_parameter_property FIFO_DEPTH_LOG2 DEFAULT_VALUE 8
set_parameter_property FIFO_DEPTH_LOG2 DISPLAY_NAME FIFO_DEPTH_LOG2
set_parameter_property FIFO_DEPTH_LOG2 TYPE INTEGER
set_parameter_property FIFO_DEPTH_LOG2 ENABLED false
set_parameter_property FIFO_DEPTH_LOG2 UNITS None
set_parameter_property FIFO_DEPTH_LOG2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH_LOG2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true

add_interface_port rst rst reset Input 1


# 
# connection point ram_w
# 
add_interface ram_w avalon start
set_interface_property ram_w addressUnits SYMBOLS
set_interface_property ram_w associatedClock clk
set_interface_property ram_w associatedReset rst
set_interface_property ram_w bitsPerSymbol 8
set_interface_property ram_w burstOnBurstBoundariesOnly false
set_interface_property ram_w burstcountUnits WORDS
set_interface_property ram_w doStreamReads false
set_interface_property ram_w doStreamWrites false
set_interface_property ram_w holdTime 0
set_interface_property ram_w linewrapBursts false
set_interface_property ram_w maximumPendingReadTransactions 0
set_interface_property ram_w readLatency 0
set_interface_property ram_w readWaitTime 1
set_interface_property ram_w setupTime 0
set_interface_property ram_w timingUnits Cycles
set_interface_property ram_w writeWaitTime 0
set_interface_property ram_w ENABLED true

add_interface_port ram_w ram_w_address address Output ADD_WIDTH
add_interface_port ram_w ram_w_waitrequest waitrequest Input 1
add_interface_port ram_w ram_w_byteenable byteenable Output BYTE_ENABLE_WIDTH
add_interface_port ram_w ram_w_write write Output 1
add_interface_port ram_w ram_w_writedata writedata Output DATA_WIDTH
add_interface_port ram_w ram_w_burstcount burstcount Output BURST_WIDTH_W


# 
# connection point ram_r
# 
add_interface ram_r avalon start
set_interface_property ram_r addressUnits SYMBOLS
set_interface_property ram_r associatedClock clk
set_interface_property ram_r associatedReset rst
set_interface_property ram_r bitsPerSymbol 8
set_interface_property ram_r burstOnBurstBoundariesOnly false
set_interface_property ram_r burstcountUnits WORDS
set_interface_property ram_r doStreamReads false
set_interface_property ram_r doStreamWrites false
set_interface_property ram_r holdTime 0
set_interface_property ram_r linewrapBursts false
set_interface_property ram_r maximumPendingReadTransactions 8
set_interface_property ram_r readLatency 0
set_interface_property ram_r readWaitTime 1
set_interface_property ram_r setupTime 0
set_interface_property ram_r timingUnits Cycles
set_interface_property ram_r writeWaitTime 0
set_interface_property ram_r ENABLED true

add_interface_port ram_r ram_r_address address Output ADD_WIDTH
add_interface_port ram_r ram_r_waitrequest waitrequest Input 1
add_interface_port ram_r ram_r_readdatavalid readdatavalid Input 1
add_interface_port ram_r ram_r_byteenable byteenable Output BYTE_ENABLE_WIDTH
add_interface_port ram_r ram_r_read read Output 1
add_interface_port ram_r ram_r_readdata readdata Input DATA_WIDTH
add_interface_port ram_r ram_r_burstcount burstcount Output BURST_WIDTH_R


# 
# connection point sis_ci
# 
add_interface sis_ci nios_custom_instruction end
set_interface_property sis_ci clockCycle 0
set_interface_property sis_ci operands 2
set_interface_property sis_ci ENABLED true

add_interface_port sis_ci cpu_clk clk Input 1
add_interface_port sis_ci cpu_rst reset Input 1
add_interface_port sis_ci cpu_clk_en clk_en Input 1
add_interface_port sis_ci cpu_start start Input 1
add_interface_port sis_ci cpu_done done Output 1
add_interface_port sis_ci cpu_addr dataa Input DATA_WIDTH
add_interface_port sis_ci cpu_addw datab Input DATA_WIDTH
add_interface_port sis_ci cpu_result result Output DATA_WIDTH
add_interface_port sis_ci n n Input 2


# 
# connection point din
# 
add_interface din avalon_streaming end
set_interface_property din associatedClock clk
set_interface_property din associatedReset rst
set_interface_property din dataBitsPerSymbol 8
set_interface_property din errorDescriptor ""
set_interface_property din firstSymbolInHighOrderBits true
set_interface_property din maxChannel 0
set_interface_property din readyLatency 1
set_interface_property din symbolsPerBeat 4
set_interface_property din ENABLED true

add_interface_port din din_data data Input 24
add_interface_port din din_ready ready Output 1
add_interface_port din din_valid valid Input 1
add_interface_port din din_sop startofpacket Input 1
add_interface_port din din_eop endofpacket Input 1

